config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'static_pages#home'

  get 'static_pages/home'

  resources :activities 
  resources :workouts
  

 
end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :activity
    belongs_to :user
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :get_activity
  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
    #  @workout = Workout.find(params[:user_id])
    # @workout.user_id = current_user
  end

  
  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
    # @activity = Activity.find(params[:id])
  end

  # GET /workouts/1/edit
  def edit

  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)
    @workout.user = current_user
      respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Your workout was logged!' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:user_id, :duration, :notes, :activity_id)
    end

    def get_activity
      @activity = Activity.all
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
  <%= simple_form_for @workout do |f| %>

    <div class="Activity">
      <%= f.input :activity_id, collection: @activity, label_method: :name, value_method: :id, label: "Activity", include_blank: true, selected: @workout.activity_id%>
      <%# <%= as: :select(:activity_id, options_from_collection_for_select(@activity, :id, :name)) %>  
    </div>

    <div class="field">
      <%= f.input :duration %>
    </div>

    <div class="field">
      <%= f.input :notes %>
    </div>

    <div class="actions">
      <%= f.button :submit %>
    </div>

    <% end %>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', edit_workout_path %>

app/views/workouts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>

    <div class="col-md-6" style="margin-top: 100px;">
        <div class="workout-index">

          <h1>Workout</h1>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Duration (minutes) </th>
                  <th scope="col">Notes (How was your session?)</th>
                  <th scope="col" colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @workouts.each do |workout| %>

                  <% if workout.user == current_user %>

                      <tr>
                      <td><%= workout.duration %></td>
                      <td><%= workout.notes %></td>
                      <td><button type="button" class="btn btn-warning"><%= link_to 'View', workout_path(workout) %></button><td>
                      </tr>
                    
                    <% end  %>
                <% end %>

              </tbody>
            </table>
    
           <button type="button" class="btn btn-primary"><%= link_to 'New Workout', new_workout_path %></button>
        </div>
    </div>

    <div class="col-md-3">
    </div>
    </div>
  </div>
</div>


   

app/views/workouts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm" style="margin-top: 100px;">
      <div class="workout-new">
          <h1>New Workout</h1>
          <br />
          <br />

          <%= render 'form', workout: @workout %>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>

app/views/workouts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm" style="margin-top: 100px;">
      <div class="workout-show">
          <p id="notice"><%= notice %></p>

          <p>
            <strong>Activity:</strong>
            <%= @activity.find(@workout.activity_id).name %>
          </p>

          <p>
            <strong>Duration:</strong>
            <%= @workout.duration %>
          </p>

          <p>
            <strong>Notes:</strong>
            <%= @workout.notes %>
          </p>

<%= link_to 'Edit', edit_workout_path(@workout) %> 
<%= link_to 'Delete', @workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>