config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'static_pages#home'

  get 'static_pages/home'

  resources :activities 
  resources :workouts
  

 
end

app/models/activity.rb
class Activity < ApplicationRecord
     has_many :workouts
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= simple_form_for @activity do |f| %>
  
  <div class="field">
    <%= f.input :name %>
  </div>


  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="activities-index">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <% if user_signed_in?  %>
          <button type="button" class="btn btn-primary"><%= link_to 'Log my workout', new_workout_path %></button>
        <% end %>
      </div>
      <div class="col-md-4">
      </div>
    </div>
      <div class="row">
      
        <div class="col-sm">
          <%= image_tag("iconrunning.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(3) %>
            <%= @activity.name %>
            </p>
        </div>
        <div class="col-sm">
          <%= image_tag("iconskating.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(4) %>
            <%= @activity.name %>
          </p> 
        </div>
        <div class="col-sm">
          <%= image_tag("iconweights.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(5) %>
            <%= @activity.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          <%= image_tag("iconcycling.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(6) %>
            <%= @activity.name %>
        </div>
        <div class="col-sm">
          <%= image_tag("mountainbike.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(7) %>
            <%= @activity.name %>
        </div>
        <div class="col-sm">
          <%= image_tag("iconswimming.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(8) %>
            <%= @activity.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          <%= image_tag("icontennis.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(9) %>
            <%= @activity.name %>
        </div>
        <div class="col-sm">
          <%= image_tag("iconvolleyball.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(10) %>
            <%= @activity.name %>
        </div>
        <div class="col-sm">
          <%= image_tag("iconbasketball.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(11) %>
            <%= @activity.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          <%= image_tag("iconsoccer.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(12) %>
            <%= @activity.name %>
        </div>
        <div class="col-sm">
          <%= image_tag("iconbaseball.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(13) %>
            <%= @activity.name %>
        </div>
        <div class="col-sm">
          <%= image_tag("iconskateboard.png", {:style => "width:80px;"}) %> 
          <p>
            <% @activity = Activity.find(14) %>
            <%= @activity.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
          <% if user_signed_in?  %>
            <button type="button" class="btn btn-primary"><%= link_to 'New Activity', new_activity_path %></button>
          <% end %>
        </div>
        <div class="col-md-4">
        </div>
        
      </div>
    </div>
</div>

app/views/activities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm" style="margin-top: 100px;">
      <div class="activity-new">
          <h1>New Activity</h1>
          <br />
          <br />

          <%= render 'form', activity: @activity %>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="container">
    <div class="row">

      <div class="col-sm">
      </div>

      <div class="col-sm">
        <div class="jumbotron">
  
          <p>
          <strong>Type:</strong>
          <%= @activity.name %>
          </p>
          

          <%= react_component 'ActivityName', {activity: @activity} %>
        </div>
      </div>

      <div class="col-sm">
      </div>

    </div>
  </div>  




 