config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'static_pages#home'

  get 'static_pages/home'

  resources :activities 
  resources :workouts
  

 
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg fixed-bottom">
  <div class="container">
      <ul class="navbar-nav mr.auto">
          <li class="nav-item"><%= link_to 'Move&Groove by: Michael Holmes', "http://holmesmichael.com" %></li>
      </ul>
      <ul class="navbar-nav ml-auto">
          <li class="nav-item"><%= link_to 'Activities', activities_path %></li>
            <% if user_signed_in? %>                 
              <li class="nav-item">  <%= link_to 'Settings', edit_user_registration_path %></li>
              <li class="nav-item">  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="nav-item"> <%= link_to 'Sign Up', new_user_registration_path %></li>
              <li class="nav-item">  <%= link_to 'Sign In', new_user_session_path %></li>
             <% end %>
  
      </ul>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-expand-lg fixed-top">
    <div class="container">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to 'Move&Groove', root_path %></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><%= link_to 'Activities', activities_path %></li>
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to 'My Workouts', workouts_path %></li>                
              <li class="nav-item"><%= link_to 'Settings', edit_user_registration_path %></li>
              <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li class="nav-item"><%= link_to 'Sign In', new_user_session_path %></li>
            <% end %>
        </ul>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movegroove</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-container">
      <%= render("layouts/navigation") %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render("layouts/footer") %>
    </div>
  </body>
</html>